apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-api
  namespace: my-api
  labels:
    app.kubernetes.io/name: my-api
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: my-api
    app.kubernetes.io/managed-by: kubectl
automountServiceAccountToken: false
